owner: orionex-solutions # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Orionex Landing Page
    url: https://orionex.id
    icon: https://storage.googleapis.com/orionex-storage/orionex.webp
  - name: Wikalpa LMS
    url: https://lms.wikalpa.orionex.id
    icon: https://lms.wikalpa.orionex.id/static/img/favicon.png
  - name: Wikalpa LMS Microservices
    url: $WIKALPA_LMS_MICROSERVICES_AI
    icon: https://lms.wikalpa.orionex.id/static/img/favicon.png
  - name: Orionex API Gateway (#1)
    url: $ORIONEX_API_GATEWAY_1
    icon: https://storage.googleapis.com/orionex-storage/orionex.webp
  - name: R&D AutoInsight by Orionex (#1)
    url: $AUTOINSIGHT_BY_ORIONEX_RND_1
    icon: https://storage.googleapis.com/orionex-storage/orionex.webp
  - name: R&D AutoInsight by Orionex (#2)
    url: $AUTOINSIGHT_BY_ORIONEX_RND_2
    icon: https://storage.googleapis.com/orionex-storage/orionex.webp
  # - name: R&D AutoInsight by Orionex (#3)
  #   url: $AUTOINSIGHT_BY_ORIONEX_RnD_3
  #   icon: https://storage.googleapis.com/orionex-storage/orionex.webp
  
  
status-website:
  cname: status.orionex.id
  theme: light
  logoUrl: https://storage.googleapis.com/orionex-storage/orionex.webp
  favicon: https://storage.googleapis.com/orionex-storage/orionex.webp
  name: Status Page
  # introTitle: "**Orionex Solutions Status Page** is the uptime monitor and status page to manage the uptime of our services."
  introMessage: This is a status page which uses **real-time** data from our services.
  navbar:
    - title: Status Page
      href: /
    - title: Homepage
      href: https://orionex.id
  customFootHtml: <p>&copy 2026 <a href=https://orionex.id>Orionex Solutions | PT Orionex Solusi Digital</a>. All rights reserved.</p>
